

/* Create Tables */

-- PROFILE_BRANCH
CREATE TABLE PROFILE_BRANCH
(
	-- 机构号
	ORG_ID VARCHAR(12) NOT NULL,
	-- 分支编码
	BRANCH_ID VARCHAR(9) NOT NULL,
	-- 上级分支
	SUPERIOR_ID VARCHAR(9),
	-- 分支名
	BRANCH_NAME VARCHAR(100) NOT NULL,
	-- 所属地区码
	ADDR_CODE VARCHAR(100),
	-- 地址
	ADDRESS VARCHAR(120),
	-- 区
	DISTRICT VARCHAR(60),
	-- 城市
	CITY VARCHAR(60),
	-- 联系电话1
	TELEPHONE1 VARCHAR(40),
	-- 联系电话2
	TELEPHONE2 VARCHAR(40),
	-- 乐观锁版本号
	JPA_VERSION INT NOT NULL,
	PRIMARY KEY (ORG_ID, BRANCH_ID)
);


-- 菜单表
CREATE TABLE PROFILE_MENU
(
	-- ID
	ID INT NOT NULL,
	-- 机构号
	ORG_ID VARCHAR(12),
	-- 菜单名称
	MNAME VARCHAR(20) NOT NULL,
	-- 菜单路径
	PATH_URL VARCHAR(500) NOT NULL,
	-- 上级菜单ID
	PARENT_ID INT DEFAULT 0 NOT NULL,
	-- 序号
	SORTN INT NOT NULL,
	-- 图标路径
	ICON VARCHAR(255),
	-- 修改时间
	MTN_TIMESTAMP TIMESTAMP,
	-- 修改用户
	MTN_USER VARCHAR(40),
	-- 乐观锁版本号
	JPA_VERSION INT NOT NULL,
	PRIMARY KEY (ID)
);


-- 密码维护历史表
CREATE TABLE PROFILE_PWD_HIST
(
	-- ID
	ID INT NOT NULL,
	-- PU_ID
	PU_ID VARCHAR(64) NOT NULL,
	-- 密码
	PASSWORD VARCHAR(300) NOT NULL,
	-- 密码建立时间
	PWD_CRE_TIME TIMESTAMP DEFAULT NOW() NOT NULL,
	-- 乐观锁版本号
	JPA_VERSION INT NOT NULL,
	PRIMARY KEY (ID)
);


-- 角色定义表
CREATE TABLE PROFILE_ROLE
(
	-- 角色ID
	ROLE_ID VARCHAR(20) NOT NULL,
	-- 机构号
	ORG_ID VARCHAR(12) NOT NULL,
	-- 分支编码
	BRANCH_ID VARCHAR(9) NOT NULL,
	-- 角色名
	ROLE_NAME VARCHAR(200) NOT NULL,
	-- 乐观锁版本号
	JPA_VERSION INT NOT NULL,
	PRIMARY KEY (ROLE_ID)
);


-- 权限表
CREATE TABLE PROFILE_ROLE_AUTH
(
	-- 角色ID
	ROLE_ID VARCHAR(20) NOT NULL,
	-- 权限标识
	AUTHORITY VARCHAR(100) NOT NULL,
	-- 权限URI
	AUTU_URI VARCHAR(500) NOT NULL,
	PRIMARY KEY (ROLE_ID, AUTHORITY)
);


-- 用户安全操作日志
CREATE TABLE PROFILE_SECOPER_LOG
(
	-- 日志序号
	LOG_ID INT NOT NULL,
	-- PU_ID
	PU_ID VARCHAR(64) NOT NULL,
	-- 操作业务类型
	OPER_TYPE VARCHAR(2) NOT NULL,
	-- IP地址
	OPER_IP VARCHAR(30) NOT NULL,
	-- 操作时间
	OPER_TIME TIMESTAMP DEFAULT NOW() NOT NULL,
	-- 乐观锁版本号
	JPA_VERSION INT NOT NULL,
	PRIMARY KEY (LOG_ID)
);


-- 用户信息表
CREATE TABLE PROFILE_USER
(
	-- PU_ID
	PU_ID VARCHAR(64) NOT NULL,
	-- 机构号
	ORG_ID VARCHAR(12) NOT NULL,
	-- 分支编码
	BRANCH_ID VARCHAR(9),
	-- 登陆ID
	USER_ID VARCHAR(40) NOT NULL,
	-- 姓名
	NAME VARCHAR(40) NOT NULL,
	-- 密码
	PASSWORD VARCHAR(300) NOT NULL,
	-- 状态
	STATUS VARCHAR(1) NOT NULL,
	-- EMAIL
	EMAIL VARCHAR(128),
	-- 密码过期日期
	PWD_EXP_DATE DATE,
	-- 密码错误次数
	PWD_TRIES INT NOT NULL,
	-- 修改时间
	MTN_TIMESTAMP TIMESTAMP DEFAULT NOW(),
	-- 修改用户
	MTN_USER VARCHAR(40),
	-- 乐观锁版本号
	JPA_VERSION INT NOT NULL,
	PRIMARY KEY (PU_ID)
);


-- 用户角色表
CREATE TABLE PROFILE_USER_ROLE
(
	-- ID
	ID INT NOT NULL,
	-- 角色ID
	ROLE_ID VARCHAR(20) NOT NULL,
	-- PU_ID
	PU_ID VARCHAR(64) NOT NULL,
	PRIMARY KEY (ID)
);



